### ISSUE TITLE
How to update deployment to new version (2021.1.3 -> 2021.1.4)

### ISSUE THREAD

**Issue by pulungw** [sassoftware/viya4-deployment#135]
In the Viya [documentation](https://go.documentation.sas.com/doc/en/itopscdc/v_017/k8sag/p0wgfbnhvyy2ddn197vzpecdedpe.htm#n09ftvvcwh9v7pn15m4k8hojjqn9), it seems there are two ways to update to a new version.

1. To use the SAS Viya Deployment Operator, see Update to a New Version Using the Deployment Operator.
2. To update a manual deployment, see Update to a New Version Manually.

Is updating to new version with viya4-deployment tool supported (and how would you do it)? Or is this tool is for initial deployment only?

Thanks.

**Comment by hahewlet** [comment]
The SAS Viya Deployment Operator is not yet integrated into viya4-deployment. In order to perform an update of Viya4, follow the Update to a New Version Manually. You can skip the following sections as viya4-deployment will cover these for you, System Requirements and Resources and New Deployment Assets. 

You must perform the manual steps in all of the relevant Deployment Notes with a few notable exceptions. I can give you a list of what to skip if I know what cadence your viya deployment at and what cadence you are updating to? If you are unsure of your cadence you can run

kubectl -n name-of-namespace get cm -o yaml | grep ' SAS_CADENCE'

When you get to Deploy the New Version, simply rerun viya4-deployment and point to your existing data directory and the updates will be applied. 

Documented Manual post-update tasks are also required. 

The plan for the future is to support Deployment Operator, which will eliminate most manual steps for the update process.

**Comment by pulungw** [comment]
Thanks for the reply. My current cadence is Stable 2021.1.3 and trying to upgrade to Stable 2021.1.4. 

I took a glance at the Deployment Notes and it looks like a lot of manual steps (I’m using the default internal postgres). If you could share what could be skipped that would be great. Although it seems it would be easier to destroy and install a brand new environment. 

Another question, when you rerun viya4-deployment do you need to manually delete all the pods? Or will Kubernetes takes care of replacing pods automatically?

Thanks.

**Comment by hahewlet** [comment]
So you will only need to follow the Deployment Notes for 2021.1.4 (Aug 2021). You can skip the entire section "Internal Instances of PostgreSQL Moving to Operator". Viya4-deployment will take care of all those changes for the customer. Any other section that is relevant for the software you have licensed need to be performed manually as documented. 

When you rerun viya4-deployment, if there is a step in the deployment notes that says to manually delete an individual pod before or after deployment you must perform that task. You don't need to manually delete all pods. If there is a new docker image present for your order in 2021.1.4, Kubernetes will take care of replacing the pods automatically.

**Comment by pulungw** [comment]
Understood, that should make it simpler. I will try and proceed. Thanks for the guidance.

**Comment by hahewlet** [comment]
@pulungw Can we close this? Have your questions been addressed?

**Comment by pulungw** [comment]
Yeah we can close this. Thanks for the help.
