### ISSUE TITLE
sas-access.properties is not being picked up into kustomization.yaml

### ISSUE THREAD

**Issue by andybouts** [sassoftware/viya4-deployment#138]
In order to configure access engines, `../sas-bases/examples/data-access/README.md ` indicates that you need 3 tranformers as well as a `sas-access.properties`, which should be added to `kustomization.yaml` as a `configMapGenerator` like shown below.

```
configMapGenerator:
- name: sas-access-config
behavior: merge
envs:
- site-config/data-access/sas-access.properties
```

This is not happening, even to the file is in the same location as the transformers (these are working as expected):
```
jumpuser@vm$ ll .../site-config/data-access/
-rw-rw-r-- 1 jumpuser jumpuser 679 Sep  2 12:01 sas-access.properties
-rw-rw---- 1 jumpuser jumpuser 550 Sep  2 13:28 deployment-access-nfs-mount.yaml
-rw-rw---- 1 jumpuser jumpuser 542 Sep  2 13:29 podTemplate-access-nfs-mount.yaml
-rw-rw---- 1 jumpuser jumpuser 567 Sep  2 13:29 cas-access-nfs-mount.yaml
``` 

Another architect told me he's having the same issue.

**Comment by andybouts** [comment]
Quick update, another architect showed me an example of how to convert the access.properties format the doc has and perform it as a patch transformer.  That worked as expected.  So, perhaps, this issue becomes an opportunity to document that process.

**Comment by enderm** [comment]
Here is a helpful resource: https://communities.sas.com/t5/SAS-Communities-Library/How-to-Configure-a-SAS-ACCESS-interface-in-SAS-Viya-4/ta-p/720888

It mentions this README: sas-bases/docs/configuring_sasaccess_and_data_connectors_for_sas_viya_4.html

@andybouts, does that cover the steps you performed?

**Comment by andybouts** [comment]
Hey @enderm , yep, that's good reference materials and mentions that env variables can be setup as configMaps, but the specific problem is that this deployment project did not use the `site-config/data-access/sas-access.properties` as documented in the `../sas-bases/examples/data-access/README.md`.  Instead, the env variables in `sas-access.properties` must be converted into a `.yaml` file so that it will be picked up as a patch transformer.

**Comment by JimBrousseau** [comment]
I am having the same issue.  Apparently kustomize version 3.7.0 has a reported bug with merging configMapGenerators.   I have found a workaround which I will provide on request, but instructions on creating a patch transformer to update the configMap would be helpful.

**Comment by thpang** [comment]
If the current examples do not work with kustomize 3.7.0 you'll have to reach out to the data-access team. They need to fix there code base. They can also provide a sample patch transformer for use.

**Comment by jkmin96** [comment]
Last time, I tried to set data-access stuff for teradataa and I thought it worked since I could run libname statement successfully.
I will try to deploy one tomorrow.

**Comment by JimBrousseau** [comment]
I created a file in the $deploy/site-config/data-access directory called configmaps.yaml.  The instructions say to modify the base kustomization.yaml file, which is impossible if using this project.  The configmaps.yaml file will be picked up during the kustomize build step and be included in the deployment.  This assumes that the sas-access-properties file is also in the $deploy/site-config/data-access directory as well as the file data-env.yaml that is copied from the $deploy/sas-bases/examples/data-access folder.

# $deploy/site-config/data-access/configmaps.yaml
apiVersion: builtin
kind: ConfigMapGenerator
behavior: merge
metadata:
  name: sas-access-config
envs:
- sas-access.properties

**Comment by JimBrousseau** [comment]
In my previous comment, the bullet should be a dash.

**Comment by jkmin96** [comment]
I will have old deployment directory.
I placed data-access directory under site-config/transformers/ and viya4-deployment added below to base kustomization.yaml
`## user defined generators
  \- site-config/transformers/data-access/sas-access-config.yaml
`
Since I don't have any working deployment now, I cannot check further. I will check more tomorrow.

**Comment by thpang** [comment]
You should be adding the `data-access` directory here: `site-config/data-access` the viya4-deployment code base will place it where it needs to go. If these samples are transformers it'll place those in the correct location when it generates the code base with kustomize.

**Comment by JimBrousseau** [comment]
Yes, that's what happened in my deployment.

--
Jim Brousseau

**Comment by JimBrousseau** [comment]
Correct.

--
Jim Brousseau

**Comment by jkmin96** [comment]
o.k. I checked what I did in more detail. 
I also did the almost same thing as what @JimBrousseau did.

I placed these files under site-config/transformers/data-access (you can place under site-config/data-access too)

- **data-env.yaml**
- data-mounts-cas.yaml
- data-mounts-deployment.yaml
- data-mounts-job.yaml
- enable-dc-ports.yaml
- enable-epcs-port.yaml
- **sas-access-config.yaml**
- sas-access.properties

I copied data-env.yaml from sas-bases/overlays/data-access/ so that viya4-deployment can pick it up and add it to kustomization.yaml.

I created sas-access-config.yaml like below since I didn't want to update kustomization.yaml manually. I also wanted viya4-deployment to pick this up and add it to the kustomization.yaml.
![image](https://user-images.githubusercontent.com/26769817/148315412-0ca45cae-a8c6-4510-8d38-c8709c1e75f6.png)

configmap of my deployment has the values in added to sas-access.properties
![image](https://user-images.githubusercontent.com/26769817/148316409-620a1514-d341-46f6-853c-452d25c73014.png)

Just like most of other READMEs, sas-bases/examples/data-access/README.md is for manual deployment (or any deployment method which requires manual update on kustomization.yaml), not for viya4-deployment.


I'm following the instruction as it is for our opensource deployments such as DDT daily deployment.
If you need, you can check our deployment directory. Please contact me if you need to check on it.

**Comment by jkmin96** [comment]
I removed sas-access-config configmap of my deployment.
I manually updated kustomization.yaml which IAC created - I added configMapGenerator part instead of using yaml file.
![image](https://user-images.githubusercontent.com/26769817/148319213-90f1bd48-87c5-4d15-82d3-5da602412529.png)

With this, I could build site.yaml successfully.
When I applied it, a new sas-access-config configmap got generated w/o problem.

**Comment by JimBrousseau** [comment]
@jkmin96 either method will work, however, kustomization.yaml will be rebuilt on the next deployment.

**Comment by jkmin96** [comment]
@JimBrousseau 
If you update kustomization.yaml manually to add configMapGenerator, yes viya4-deployment will create a new kustomization.yaml removing it.

If you use a yaml like my sas-access-config.yaml (I guess you also use it), I think we can run viya4-deployment w/o problem.

**Comment by thpang** [comment]
Hi @jkmin96 checking for clarification. You were able to include the items listed in their own directory under site-config and have the DAC tooling apply those items into the kustomization.yaml and site.yaml without any issues, correct?

**Comment by JimBrousseau** [comment]
Yes, that is correct.

--
Jim Brousseau

**Comment by thpang** [comment]
If that's the case I'll close this one. Andy is no longer with the company.

**Comment by biohazd** [comment]
@JimBrousseau   How did you fix this issue?

I have set 
ORACLE:   /access-clients/oracle/instantclient_19_8

How do I add access-clients/oracle/instantclient_19_8 to "$LD_LIBRARY_PATH". ?


```
360  proc sql;
361    connect to oracle (user='admin' password=XXXXXXXXXXXXXXXXXXXXXX path='dsdfdf.bx9.eu-west-2.rds.amazonaws.com');
ERROR: Unable to load oracle client (libclntsh.so)
ERROR: A Connection to the oracle DBMS is not currently supported, or is not installed at your site.
NOTE: PROC SQL set option NOEXEC and will continue to check the syntax of statements
```
