### ISSUE TITLE
unable to deploy viya4-development from trial license

### ISSUE THREAD

**Issue by zencircle** [sassoftware/viya4-deployment#178]
I am unable to download assets, I have created PR on viya-orders-cli. Please see the notes on the discussion https://github.com/sassoftware/viya4-orders-cli/pull/21 and let me know team thoughts on updating the readme.md

**Comment by thpang** [comment]
@zencircle, was your order created for internal or external use?

**Comment by zencircle** [comment]
> @zencircle, was your order created for internal or external use?

https://www.sas.com/en_hk/trials.html. I used this link to place order

**Comment by sayeun** [comment]
As you pointed out already downloading assets is not part of the viya-deployment project, its part of viya4-orders-cli.  We don't want to add note to tell what the other project's support.  That is because we don't know if/when the other project makes update or change behavior. We should not document other project's dos and don'ts. 
Closing this issue.
