### ISSUE TITLE
Can we use Ansible script to update SAS software from one LTS to other ?

### ISSUE THREAD

**Issue by sandeepgrande** [sassoftware/viya4-deployment#183]
Can we use Ansible script to update SAS software from one LTS to other ?

**Comment by thpang** [comment]
Yes, there should be no issues. As long as you adjust your ansible-vars.yaml file with the updated order the new `kustomization.yaml` and `site.yaml` file that would be applied into the running cluster. I would also check the official documentation as some of the underlying elements of the cluster have changed since the last LTS release which might require other items, like your ingress-nginx, to be updated. If that's the case you'd need to scale down your SAS Viya software, and update the baseline, then scale SAS Viya back up and apply the newest LTS.  You'll definitely need to reference this [document](https://go.documentation.sas.com/doc/en/itopscdc/v_025/k8sag/titlepage.htm) published by SAS.
