### ISSUE TITLE
(IAC-485) Customizations incorrectly added to kustomization.yaml

### ISSUE THREAD

**Issue by hyweldaniels** [sassoftware/viya4-deployment#184]
When applying a customization, in this case specifically the _schedule-start-stop.yaml_ transformer from _sas-bases/examples/kubernetes-tools/lifecycle-operations/schedule-start-stop_, the transformer entry is added **before** the required transformers entry.  However the readme states that it must be added **after** the required transformers entry.

```
**Note:** This file should be included *after* the line
- sas-bases/overlays/required/transformers.yaml
```

The impact of it being above is that the _sas-stop-all_ job will incorrectly suspend the _sas-start-all_ and _sas-stop-all_ cronjobs, meaning that any scheduled startup will not occur.

**Comment by hyweldaniels** [comment]
I'll also add that I reproduced the behavior in release 4.4.0 (the release the customer used to deploy) as well as the latest 4.6.0 release.  The behavior was consistent for both.

**Comment by shealym** [comment]
I just started admin of a client who has 2021.2 installed using viya4-deployment, and am hitting this same issue.  In order to work around this (or other cases where the autogenerated kustomization.yaml isn't correct), is it generally ok to:

a) set "DEPLOY: false" and let viya4-deployment build everything it can properly
b) edit the kustomization.yaml manually to bypass an issue like this
c)  follow the typical manual-deployment "kubectl apply" steps to load the update?

Or are there reasons that wouldn't be a good idea...

Thanks for the help!

**Comment by mikegigawatt** [comment]
@shealym I have used that exact approach to fix issues with kustomization.yaml and it has worked well for me. I haven't seen a down side to it yet, and I check back every so often to see i the issues are fixed in the code so that I can go back to automatically deploying.

**Comment by sayeun** [comment]
We are currently placing this in our next sprint which will start end of July.
