### ISSUE TITLE
MountVolume.SetUp failed for volume "pv-nfs-subdir-external-provisioner" : mount failed: exit status 32

### ISSUE THREAD

**Issue by lorenzk1213** [sassoftware/viya4-deployment#228]
Hi,

After executing the baseline install to install the prerequisites using the viya4-deployment DAC scripts. I have observed there seems to be something wrong with nfs

![image](https://user-images.githubusercontent.com/104424321/169766685-804f6360-dabf-491d-a527-d4ce0e71115c.png)

![image](https://user-images.githubusercontent.com/104424321/169766968-731af273-43ec-4382-afcb-b988dafe85c1.png)

Seems relating to mounting. But not sure.
Any suggestions here pls? Attaching full describe of the pod
[nfs_describe.log](https://github.com/sassoftware/viya4-deployment/files/8752409/nfs_describe.log)

Thanks in advance

**Comment by thpang** [comment]
Can the nodes communicate with the NFS server?

**Comment by lorenzk1213** [comment]
To add.. this EFS is an encrypted EFS with KMS holding the certificate. Probably if I can also seek direction on how to mount the encrypted EFS would be good also.

**Comment by ladorval** [comment]
Building the Viya-deployment image was failing because git could not be found.
![gitNotFound](https://user-images.githubusercontent.com/7584400/172502582-cde24ac9-cafb-4321-835b-6c4de2250872.png)

Adding git to the list of utilities to apt install in the Dockerfile helped.
![added git in the list of things to apt install](https://user-images.githubusercontent.com/7584400/172502543-46b2cedc-c799-4f33-8da9-7d2cfda5a623.png).  Is this the right thing to do?

**Comment by dhoucgitter** [comment]
@ladorval, in the current version of the DAC Dockerfile (many versions later than yours), `git` is being installed after the "#Add extra packages" comment. Were you eventually able to successfully build your image?

**Comment by dhoucgitter** [comment]
Marking as stale/inactive. If there are further questions please open a new [GitHub issue](https://github.com/sassoftware/viya4-deployment/issues/new/choose).
