### ISSUE TITLE
feat: (IAC-1286) naming of Load balancer in AWS

### ISSUE THREAD

**Issue by biohazd** [sassoftware/viya4-deployment#476]
Please can you name the NLB created in AWS the same as all other resoruces, namely with the {{ NAMESPACE }}

currently it uses random numbers and letters:
e.g. ae3644443b85esfd809084sdfsdf

new naming:
{{ NAMESPACE }}-nlb

**Comment by jarpat** [comment]
This requires PM review

**Comment by jarpat** [comment]
Closing this, we decided to document to end users how to set the tags in the `INGRESS_NGINX_CONFIG` so that it would get picked up by the LoadBalancer.
See https://github.com/sassoftware/viya4-deployment/blob/main/docs/Troubleshooting.md#tagging-the-aws-ec2-load-balancers

In short you can add:

`service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "mytag=foo,anothertag=anothervalue"`
To the annotations section to add any addtional tags for the AWS LB
https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.3/guide/service/annotations/#additional-resource-tags

There is no plans to add functionality to set the name of the LB as of now, the `service.beta.kubernetes.io/aws-load-balancer-name"` annotation may be able to set it, but I believe the AWS Load Balancer Controller add-on is required which we also have no plans to add yet. If changes come in the future our doc will be updated.
